In [1]:
#inport pacakages 
import numpy as np
import matplotlib.pyplot as plt


In [39]:
theta = np.array([[0, 1, 2]])

x = np.array([[1, 0, 1],[1, 1, 1],[1, 1, -1],[-1, 1, 1]])
y = np.array([2, 2.7, -0.7, 2])

print(x)

[[ 1  0  1]
 [ 1  1  1]
 [ 1  1 -1]
 [-1  1  1]]


Compute Hinge Loss

In [ ]:
def single_hinge(x,y,theta):
    return max(0, 1 -  (y - np.dot(theta, x)))

In [42]:
for i in range (0, 4):
    print(single_hinge(x[i], y[i], theta))

[1.]
[1.3]
[0.7]
[2.]


In [45]:
def hinge_loss(x, y, theta, N):
    l = 0
    for i in range (0, N):
        a = single_hinge(x[i], y[i], theta)
        l += a
    return l/N

In [54]:
hinge_loss(x, y, theta, 4)

array([1.25])

Compute Squared Error Loss

In [63]:
def squared_error_loss(x, y, theta, N):
    l = 0
    for i in range(0,N):
        a = (1/N)*((y[i] - np.dot(theta, x[i]))**2/2)
        l += a
    return l        

In [64]:
squared_error_loss(x,y,theta,4)

array([0.1475])

In [ ]:
print(((1-0.4*0))*(y[1] - np.dot(theta, x[1])) * x[1])


SyntaxError: unmatched ')' (3578600815.py, line 1)

In [13]:
x = np.array([1,0,0])
x_l = np.array([0,1,0])

print((-1/2)*(np.linalg.norm((x-x_l))**2)) 

-1.0000000000000002


In [24]:
np.matrix([[3],[2],[1]]) *np.matrix([[1,2,1]])

matrix([[3, 6, 3],
        [2, 4, 2],
        [1, 2, 1]])